// <auto-generated />
using Dept.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dept.Repository.Migrations
{
    [DbContext(typeof(DeptContext))]
    partial class DeptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Dept.Domain.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Nome = "Recursos Humanos",
                            Telefone = "222-3535"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Financeiro",
                            Telefone = "222-3535"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Administrativo",
                            Telefone = "222-3535"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Comercial",
                            Telefone = "222-3535"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Manutenção",
                            Telefone = "222-3535"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Operacional",
                            Telefone = "222-3535"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "TI",
                            Telefone = "99704-6172"
                        });
                });

            modelBuilder.Entity("Dept.Domain.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 16,
                            Nome = "Fabio",
                            Sobrenome = "Fernandes",
                            Telefone = "555-3626"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 16,
                            Nome = "José",
                            Sobrenome = "da Silva",
                            Telefone = "888-9899"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 16,
                            Nome = "Thiago",
                            Sobrenome = "Oliveira",
                            Telefone = "964-5896"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 16,
                            Nome = "Paloma",
                            Sobrenome = "Machado",
                            Telefone = "562-5233"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 16,
                            Nome = "Laura",
                            Sobrenome = "Ferreira",
                            Telefone = "548-8986"
                        },
                        new
                        {
                            Id = 6,
                            DepartamentoId = 16,
                            Nome = "Lucas",
                            Sobrenome = "Paula",
                            Telefone = "111-2350"
                        },
                        new
                        {
                            Id = 7,
                            DepartamentoId = 16,
                            Nome = "Edite",
                            Sobrenome = "Fernandes",
                            Telefone = "225-6583"
                        });
                });

            modelBuilder.Entity("Dept.Domain.Funcionario", b =>
                {
                    b.HasOne("Dept.Domain.Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Dept.Domain.Departamento", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
